### PR TITLE
Fix #39: Replace typings with @types by npm

### LINKED ISSUE #39: Compilation error due to update of type definitions
ref: #38

### PR DESCRIPTION
**Pull request by chitoku-k**
Confirmed that build and lint work on macOS 10.12.4 with npm 0.2.0.

Refer to: https://github.com/rhysd/NyaoVim/pull/115

### CODE REVIEW

**Comment by rhysd** [comment]
Thank you.I also confirmed this works. Although installing node-canvas failed, it looks not related to this change.

**Comment by chitoku-k** [comment]
@rhysd 
`node-canvas` requires following steps on my environment:
1. Install `fontconfig`
2. Run `CXX=/usr/bin/g++ -I/usr/local/include npm i node-canvas`

**Comment by rhysd** [comment]
oh... So I think header path should be set manualy... Thank you for the info.

And I'll remove typings.json also.
